name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - deploy # Se activa solo en la rama exigida por la pauta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_FRONT_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            # Detener contenedor anterior si existe
            docker stop innovatech_frontend || true
            docker rm innovatech_frontend || true
            # Descargar la nueva versión desde el registro
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
            # Ejecutar el nuevo contenedor en el puerto 80
            docker run -d --name innovatech_frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest